-- Drop all existing tables to prepare for clean bootstrap
-- All tables are empty (verified), so no data loss
DROP VIEW IF EXISTS public_availability CASCADE;
DROP TABLE IF EXISTS booking_internal_notes CASCADE;
DROP TABLE IF EXISTS email_automation_sends CASCADE;
DROP TABLE IF EXISTS email_automations CASCADE;
DROP TABLE IF EXISTS email_templates CASCADE;
DROP TABLE IF EXISTS email_settings CASCADE;
DROP TABLE IF EXISTS payment_events CASCADE;
DROP TABLE IF EXISTS payment_settings CASCADE;
DROP TABLE IF EXISTS account_settings CASCADE;
DROP TABLE IF EXISTS cleaning_tasks CASCADE;
DROP TABLE IF EXISTS maintenance_notes CASCADE;
DROP TABLE IF EXISTS inquiries CASCADE;
DROP TABLE IF EXISTS notification_logs CASCADE;
DROP TABLE IF EXISTS owner_blocks CASCADE;
DROP TABLE IF EXISTS date_availability_overrides CASCADE;
DROP TABLE IF EXISTS date_price_overrides CASCADE;
DROP TABLE IF EXISTS day_of_week_rates CASCADE;
DROP TABLE IF EXISTS seasonal_pricing_presets CASCADE;
DROP TABLE IF EXISTS property_fees CASCADE;
DROP TABLE IF EXISTS pricing_rules CASCADE;
DROP TABLE IF EXISTS blocked_dates CASCADE;
DROP TABLE IF EXISTS ical_sources CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS local_recommendations CASCADE;
DROP TABLE IF EXISTS property_policies CASCADE;
DROP TABLE IF EXISTS house_rules CASCADE;
DROP TABLE IF EXISTS faqs CASCADE;
DROP TABLE IF EXISTS neighborhood_highlights CASCADE;
DROP TABLE IF EXISTS contact_info CASCADE;
DROP TABLE IF EXISTS photo_section_features CASCADE;
DROP TABLE IF EXISTS photo_sections CASCADE;
DROP TABLE IF EXISTS property_images CASCADE;
DROP TABLE IF EXISTS property_amenities CASCADE;
DROP TABLE IF EXISTS amenities CASCADE;
DROP TABLE IF EXISTS amenity_categories CASCADE;
DROP TABLE IF EXISTS sleeping_arrangements CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS highlights CASCADE;
DROP TABLE IF EXISTS properties CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Drop functions
DROP FUNCTION IF EXISTS cleanup_expired_pending_payment_bookings() CASCADE;
DROP FUNCTION IF EXISTS auto_archive_old_bookings() CASCADE;
DROP FUNCTION IF EXISTS cleanup_old_inquiries() CASCADE;
DROP FUNCTION IF EXISTS payment_settings_upsert_secret(text, text) CASCADE;
DROP FUNCTION IF EXISTS payment_settings_get_secret(text) CASCADE;
DROP FUNCTION IF EXISTS payment_settings_secret_exists(text) CASCADE;
DROP FUNCTION IF EXISTS payment_settings_secret_preview(text) CASCADE;
DROP FUNCTION IF EXISTS payment_settings_delete_secret(text) CASCADE;
DROP FUNCTION IF EXISTS update_payment_settings_updated_at() CASCADE;
DROP FUNCTION IF EXISTS email_settings_upsert_secret(text, text) CASCADE;
DROP FUNCTION IF EXISTS email_settings_get_secret(text) CASCADE;
DROP FUNCTION IF EXISTS email_settings_delete_secret(text) CASCADE;
DROP FUNCTION IF EXISTS email_settings_secret_exists(text) CASCADE;
DROP FUNCTION IF EXISTS email_settings_secret_preview(text) CASCADE;
DROP FUNCTION IF EXISTS update_email_settings_updated_at() CASCADE;
